### ISSUE TITLE
html_show_sphinx not working

### ISSUE THREAD

**Issue by mohan43u** [sphinx-doc/alabaster#172]
If I set [html_show_sphinx](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_sphinx), Rendered output is not suppose to show *Powered By* at the bottom, but Alabaster theme expects theme specific *show_powered_by* option to disable.

Add support to  [html_show_sphinx](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_sphinx)

**Comment by wxrl** [comment]
Same here.
Also `html_show_copyright` and `html_show_sourcelink` not working. (even rebuild after `rm -R build`)
using sphinx 4.0.1 and `pydata_sphinx_theme`.
