### ISSUE TITLE
Building Sphinx 6.1.3 fails with `app.require_sphinx("1.6")`

### ISSUE THREAD

**Issue by polyzen** [sphinx-doc/alabaster#201]
https://github.com/sphinx-doc/alabaster/blob/0.7.13/alabaster/__init__.py#L19
For some reason this results in a test failure when building Sphinx 6.1.3:
`sphinx.errors.VersionRequirementError: The alabaster extension used by this project needs at least Sphinx v1.6; it therefore cannot be built with this version.`

Using the following build script:
https://github.com/archlinux/svntogit-community/blob/d6ca41cc1d2b0e3a8b9be4752e4a6d02c1f76143/trunk/PKGBUILD

**Comment by AA-Turner** [comment]
I've tested locally and I don't get an error on building documentation with Sphinx 6.2 and alabaster's HEAD. Is this restricted to just 6.1.3? Would you be able to provide a minimal reproducer -- I can't tell which bit of the build script is failing.

A

**Comment by polyzen** [comment]
It's not with building documentation, it's with building the Sphinx package itself.

**Comment by AA-Turner** [comment]
So ``python -m build`` fails?

**Comment by polyzen** [comment]
I had been building Sphinx against Alabaster patched via `sed -i '/app.require_sphinx("1.6")/d' alabaster/__init__.py` since 6.1.3. Just built 6.2.1 without that "patch", and appears this has been resolved upstream.
