### ISSUE TITLE
``OldJinjaSuffixWarning`` for ``alabaster.css_t`` in unreleased Sphinx 6.2

### ISSUE THREAD

**Issue by bsipocz** [sphinx-doc/alabaster#203]
I see the following warning, that our CI treats as error:

Do you foresee any issues with renaming the file?

```
 Warning, treated as error:
Failed to copy a file in html_static_file: /home/runner/work/sphinx-automodapi/sphinx-automodapi/.tox/py310-test-sphinxdev/lib/python3.10/site-packages/alabaster/static/alabaster.css_t: OldJinjaSuffixWarning("'/home/runner/work/sphinx-automodapi/sphinx-automodapi/.tox/py310-test-sphinxdev/lib/python3.10/site-packages/alabaster/static/alabaster.css_t': the '_t' suffix for Jinja templates is deprecated. If the file is a template, use the suffix '.jinja' instead. For more information, see https://www.sphinx-doc.org/en/master/development/theming.html#static-templates")
```

https://github.com/astropy/sphinx-automodapi/actions/runs/4694556705/jobs/8322825594#step:8:170

x-ref: https://github.com/astropy/sphinx-automodapi/issues/164

**Comment by AA-Turner** [comment]
Alabaster should supress this warning -- if we keep it. Currently the warning only exists in Sphinx HEAD, so for now I'll keep this open, but we won't be renaming the file.

A
