### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by domenkozar** [sphinx-doc/alabaster#207]

**Comment by domenkozar** [comment]
Why is it spam, the url in the source doesn't work anymore: https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png

**Comment by domenkozar** [comment]
The problem is that this URL used is not longer there.

Alternative would be to use something like 

https://github.com/simonwhitaker/github-fork-ribbon-css

**Comment by greg-finley** [comment]
We hit the same issue: https://github.com/sqlfluff/sqlfluff/issues/4987
