### ISSUE TITLE
forkme image working

### ISSUE THREAD

**Issue by jbloom** [sphinx-doc/alabaster#208]
The `github_banner` option links to the following image: https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png

However, no such image exists on S3 anymore, so no image shows up and the page looks wrong.

**Comment by alexdlaird** [comment]
GitHub moved their images to this URL instead: But GitHub actually serves up these images themselves, point to this URL instead: https://github.blog/wp-content/uploads/2008/12/forkme_right_darkblue_121621.png

**Comment by Michael-E-Rose** [comment]
Thanks for the workaround!

But how do you know they don't accept changes? The last PR https://github.com/sphinx-doc/alabaster/pulls?q=is%3Apr+is%3Aclosed was merged 2 weeks ago.

**Comment by alexdlaird** [comment]
That was an assumption on my part after looking at various issues / PRs with no response on them, but perhaps they do! Would be great if they merged a fix for this, since it's relatively simple.

**Comment by jbloom** [comment]
Has anyone actually opened a pull request for this, or should I?

**Comment by Michael-E-Rose** [comment]
Looks like a "no" so far. Go for it, I will be forever grateful :)

**Comment by jbloom** [comment]
I opened #211 to fix this.

Hopefully they will merge it soon!
